### ISSUE TITLE
Need some advice about Coherent indexes

### ISSUE THREAD

**Issue by javafanboy** [oracle/coherence#67]
A need some general advice on how Indexes work from a consistency and backup point of view? Lets say I update some data spread over multiple partitions using an entry processor - when are the indexes updated with those changes?
Also are Coherence indexes backed up over several nodes (how many, asynch or synch...)?

**Comment by thegridman** [comment]
Indexes are updated at the same time an entry is mutated. So a slow value extractor used for an index can impact write performance (and yes we have seen people try to access a DB from an index extractor 😮). Indexes are not backed up so when a partition moves, due to redistribution on member join or member left, then the indexes are rebuilt for the moved partitions.

**Comment by javafanboy** [comment]
Thanks - that was basically what I was hoping for.

While indexes are re-rebuilt will queries making use of them be "suspended"
or fail?

**Comment by thegridman** [comment]
Queries are blocked until the index has finished building. 
Releated to your other questions about reading from nearest cluster member, queries will always execute on the primary owners. This makes sense really as a query is cluster wide anyway so will run on all cluster members (unless it is a partitioned query, which is restricted to specific partitions).
